tosca_definitions_version: cloudify_dsl_1_1

imports:
- http://www.getcloudify.org/spec/cloudify/3.2rc1/types.yaml

plugins:
  cloudfoundry:
    executor: central_deployment_agent
    source: https://github.com/GigaSpaces-POCs/cfy-pivotal/archive/v0.2.1.zip

inputs:

  anyninesEndpoint:
    type: string
    default: 'api.de.a9s.eu'
  anyninesPassword:
    type: string
    default: ''
  anyninesSpace:
    type: string
    default: production-space
  anyninesOrganization:
    type: string
    default: ''
  anyninesUsername:
    type: string
    default: ''
  applicationName:
    type: string
    default: 'Cloudify Webapp'
  color1:
    type: string
    default: red
  color2:
    type: string
    default: green
  color3:
    type: string
    default: #0000FF
  pivotalEndpoint:
    type: string
    default: 'api.run.pivotal.io'
  pivotalOrganization:
    type: string
    default: ''
  pivotalPassword:
    type: string
    default: ''
  pivotalSpace1:
    type: string
    default: left-space
  pivotalSpace2:
    type: string
    default: right-space
  pivotalUsername:
    type: string
    default: ''

node_types:

  cloudify.cloudfoundry.provider:
    derived_from: cloudify.nodes.Container
    properties:
      endpoint: {}
      username: {}
      password: {}

  cloudify.cloudfoundry.space:
    derived_from: cloudify.cloudfoundry.provider
    properties:
      organization: {}
      space: {}

  cloudify.cloudfoundry.app:
    derived_from: cloudify.nodes.WebServer
    properties:
      application_name: {}
      color: {}

relationships:

  cloudify.cloudfoundry.deployment:
    derived_from: cloudify.relationships.contained_in
    source_interfaces:
      cloudify.interfaces.relationship_lifecycle:
        preconfigure: scripts/login.sh
        establish: scripts/cf-push.sh

node_templates:

  # CloudFoundry PaaS providers

  pivotal-io:
    type: cloudify.cloudfoundry.provider
    properties:
      install_agent: false
      endpoint: { get_input: pivotalEndpoint }
      username: { get_input: pivotalUsername }
      password: { get_input: pivotalPassword }

  anynines:
    type: cloudify.cloudfoundry.provider
    properties:
      install_agent: false
      endpoint: { get_input: anyninesEndpoint }
      username: { get_input: anyninesUsername }
      password: { get_input: anyninesPassword }

  # spaces belonging to this implementation on the PaaS accounts

  left-space:
    type: cloudify.cloudfoundry.space
    properties:
      install_agent: false
      endpoint: { get_input: pivotalEndpoint }
      username: { get_input: pivotalUsername }
      password: { get_input: pivotalPassword }
      organization: { get_input: pivotalOrganization }
      space: { get_input: pivotalSpace1 }
    relationships:
      - type: cloudify.relationships.contained_in
        target: pivotal-io

  right-space:
    type: cloudify.cloudfoundry.space
    properties:
      install_agent: false
      endpoint: { get_input: pivotalEndpoint }
      username: { get_input: pivotalUsername }
      password: { get_input: pivotalPassword }
      organization: { get_input: pivotalOrganization }
      space: { get_input: pivotalSpace2 }
    relationships:
      - type: cloudify.relationships.contained_in
        target: pivotal-io

  prod-space:
    type: cloudify.cloudfoundry.space
    properties:
      install_agent: false
      endpoint: { get_input: anyninesEndpoint }
      username: { get_input: anyninesUsername }
      password: { get_input: anyninesPassword }
      organization: { get_input: anyninesOrganization }
      space: { get_input: anyninesSpace }
    relationships:
      - type: cloudify.relationships.contained_in
        target: anynines

  # app deployments in the spaces

  rails1:
    type: cloudify.cloudfoundry.app
    properties:
      application_name: { get_input: applicationName }
      color: { get_input: color1 }
    relationships:
      - type: cloudify.cloudfoundry.deployment
        target: left-space

  rails2:
    type: cloudify.cloudfoundry.app
    properties:
      application_name: { get_input: applicationName }
      color: { get_input: color2 }
    relationships:
      - type: cloudify.cloudfoundry.deployment
        target: right-space

  rails3:
    type: cloudify.cloudfoundry.app
    properties:
      application_name: { get_input: applicationName }
      color: { get_input: color3 }
    relationships:
      - type: cloudify.cloudfoundry.deployment
        target: prod-space

workflows:

  ## Note that scale_up is only temporary and will be mapped back to Cloudify's
  ## built-in scale operation once a manager plugin has been provided.

  sister:
    mapping: cloudfoundry.workflows.scale
    parameters:
      node_instance_ids:
        description: >
          The instance ids to scale. These would be a list of node.id values
          that we want to scale: e.g. [rails1_12333, rails2_61b57, ...]
        default: []
      node_ids:
        description: >
          The node_ids to scale. We want the list of node.node_id values that
          we want to scale: e.g. [rails1, rails2, ...]
        default: []
      delta:
        description: >
          The number of instances to add (if positive) or subtract (if negative)
          from the provider's pool of app instances.
        default: 0